### ISSUE TITLE
Error: https://json-schema.org/draft/2020-12/schema is not a schema. Found a document with media type: application/octet-stream

### ISSUE THREAD

**Issue by HanojHanu** [hyperjump-io/json-schema-core#10]
![image](https://user-images.githubusercontent.com/53425981/149710325-9f17a0aa-1824-40a1-ab1f-02569edddafe.png)

**Comment by jdesrosiers** [comment]
I'm guessing you're looking for a JSON Schema validator that supports 2020-12. You'll find that at https://github.com/hyperjump-io/json-schema-validator. This package is used to create custom dialects and probably not what you are looking for. If I'm wrong, please ask a question and I'll do my best to help.

**Comment by HanojHanu** [comment]
Hi @jdesrosiers,

Thanks for your response.

But we are using this package in our Node.js Project ( package version is [@hyperjump/json-schema@0.11.1](https://bundlephobia.com/package/@hyperjump/json-schema@0.11.1) ).

After deployment, this project in AWS lambda shows project size is more them 3.2 MB.

Because of this https://bundlephobia.com/package/@hyperjump/json-schema@0.11.1

Can please help me on this.

**Comment by jdesrosiers** [comment]
I think you meant to make that comment on https://github.com/hyperjump-io/json-schema-validator/issues/13
