### ISSUE TITLE
Default Schema Version

### ISSUE THREAD

**Issue by jawaff** [hyperjump-io/json-schema-core#12]
I might be understanding this incorrectly, but it looks like there's support for pulling the schema version out of a Content-Type parameter. For context, we're hosting our json schemas in a web server and trying to validate against them in our frontend. One problem is that our schemas can't have a "$schema" property because they're technically subschemas since they are referenced by some openapi specs. The json schema spec says that "$schema" shouldn't be in subschemas and the library we're using for hosting, Vertx, doesn't like seeing "$schema" in the subschemas. So we went down the route of putting the schema version into a response header.

We thought it'd work since this library seems to support the Content-Type parameters, but we ran into an exception when we attempted a "JsonSchema.get()". It appears that the "JsonSchema.get()" is handling the "defaultDialectId" a bit differently than the "JsonSchema.add()" and the "resolveUrl()" call is throwing an exception before it gets a chance to fall back to the "defaultDialectId".

https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.11.2

https://github.com/hyperjump-io/json-schema-core/blob/eac463556a47a1b6394c4950e2627e3bdd48dec3/lib/schema.js#L206

![Image Pasted at 2022-8-5 17-55](https://user-images.githubusercontent.com/2895324/183218417-1f145bc8-13ce-4bbd-bfff-cd122f58f744.png)

I think I know the solution, but I'm not entirely sure. We currently have this for the "dialectId" handling in the "JsonSchema.get()":
```
    const [schema, defaultDialectId] = await MediaTypes.parse(response);

    // Make sure the meta-schema is loaded if this isn't a known dialect
    const dialectId = resolveUrl(schema.$schema, "") || defaultDialectId;
    if (id !== dialectId && !(dialectId in dialectJsonSchemaVersion)) {
      await get(dialectId);
    }
```

Would this be a possible fix? I'm not sure what the difference between the "defaultDialectId" and the "defaultSchemaVersion" in the "JsonSchema.add()" function are, but maybe this would work? The other option is just doing a check to see if the "$schema" is present or not and fall back to the "defaultDialectId" if it's not present.
```
    const [schema, defaultDialectId] = await MediaTypes.parse(response);

    // Make sure the meta-schema is loaded if this isn't a known dialect
    const dialectId = resolveUrl(schema["$schema"] || defaultDialectId, "");
    if (id !== dialectId && !(dialectId in dialectJsonSchemaVersion)) {
      await get(dialectId);
    }
```

**Comment by jdesrosiers** [comment]
I actually just add support for this feature a couple days ago. It looks like I need to add a few more test cases.

**Comment by jdesrosiers** [comment]
I just published a fix. Let me know if you have any further issues.
