### ISSUE TITLE
Unhandled Promise Rejections with multiple unresolved $refs

### ISSUE THREAD

**Issue by ogoldman** [hyperjump-io/json-schema-core#2]
I have a short script that loads the schema below from a file, then attempts to validate an instance document against it. If I remove the definition of property "b", then this schema will fail to validate, as expected. The error message is:

> request to http://example.com/schema/2 failed, reason: getaddrinfo ENOTFOUND example.com

However, in its full form, I will receive first the error above, followed by an unhandled promise rejection:

> (node:219) UnhandledPromiseRejectionWarning: FetchError: request to http://example.com/schema/3 failed, reason: getaddrinfo ENOTFOUND example.com

I believe this is an error, in that the library should either return a single error (for the unresolved $ref) or a single rejection (perhaps with a list of $ref failures). (I have a feeling maybe a Promise.allSettled is missing, but that's just a guess.) Alternatively, it may be that I don't understand the API contract for JsonSchema.validate(), in which case I'd appreciate an explanation. I'm simply using:

> const output = await JsonSchema.validate(schema, instanceJSON, JsonSchema.VERBOSE);

For context: I am attempting to apply a set of related schemas that use $id and $ref with schema identifiers that, as in the example below, are not network locations. If a explicitly load the various schemas, everything works. I encountered this when I $ref'ed a schema that hadn't been loaded. That's an error on my part, but one I'd like my script to catch "cleanly" and report.

`{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "http://example.com/schema/1",
      "properties": {
        "a": { "$ref": "http://example.com/schema/2" },
        "b": { "$ref": "http://example.com/schema/3" }
    }
}`

**Comment by jdesrosiers** [comment]
Thanks, I'm looking into it.

**Comment by jdesrosiers** [comment]
I just published v0.8.0. I'm pretty sure this fixes the problem, but please check and let me know if it's working for you. You should expect the error to be for whichever request returns first. The second error is ignored and should not trigger an UnhandledPromiseRejectionWarning.

**Comment by ogoldman** [comment]
Thanks--I will try to get back to this in the next day or two to evaluate.

**Comment by ogoldman** [comment]
Confirmed--I'm now only receiving one error. (It would be ideal to get the list, but that is beyond the scope of this specific issue.)
