### ISSUE TITLE
Invalid type value results in an undefined error

### ISSUE THREAD

**Issue by ogoldman** [hyperjump-io/json-schema-core#3]
I'm seeing an "undefined" error in a case where the schema is invalid, but I'd expect to get an error message directing me to the error at hand. Here's the invalid schema:

```
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "http://example.com/test",
    "properties": {
        "a": { "type": "date-time" }
    }
}

```

If I fix this by changing the type of "a" to "string", then the schema loads and I can validate instance documents. With this error, the schema will load, but when I validate a document, it throws `undefined`.

**Comment by jdesrosiers** [comment]
I'm not able to reproduce this one. The expected result is for it to throw the result of meta-validation. When I attempt to validate that schema I get the following error.

```
{
  keyword: 'http://json-schema.org/draft-06/schema#validate',
  absoluteKeywordLocation: 'http://json-schema.org/draft-06/schema#',
  instanceLocation: 'http://example.com/test#',
  valid: false,
  errors: [
    {
      keyword: 'http://json-schema.org/draft-06/schema#additionalProperties',
      absoluteKeywordLocation: 'http://json-schema.org/draft-06/schema#',
      instanceLocation: 'http://example.com/test#/properties',
      valid: false,
      errors: [Array]
    },
    {
      keyword: 'http://json-schema.org/draft-06/schema#properties',
      absoluteKeywordLocation: 'http://json-schema.org/draft-06/schema#/properties',
      instanceLocation: 'http://example.com/test#',
      valid: false,
      errors: [Array]
    }
  ]
}
```

**Comment by ogoldman** [comment]
OK--thanks for investigating. I'll take another look at my code, and then provide an update here.

**Comment by ogoldman** [comment]
Alright, here's what I got tripped up on. When I call validate:

`const output = await JsonSchema.validate(schema, instanceJSON, JsonSchema.VERBOSE);`

If the schema fails to validate, then this throws--but it doesn't throw an Error. Instead, it throws an output object for the schema. Is this the intended behavior?

**Comment by jdesrosiers** [comment]
Yes, that's the expected behavior. I've never been happy with the way meta-validation errors are handled. Throwing the output was intended to be temporary until I came up with something I liked better, but I haven't come up with anything yet, so it's still there. I wanted to avoid having to make a custom error implementation, but at this point I should probably do that or prioritize coming up with an approach I like better.

**Comment by ogoldman** [comment]
Got it. As a client, I think the throw seems reasonable, but not extending Error definitely tripped me up. I would have expected a custom error from which I could retrieve the output object.

Do you want me to close this? Or leave it open as a reminder to revisit this? :)

**Comment by jdesrosiers** [comment]
Thanks for the feedback. You can leave it open. I'm not sure what I'm going to do yet, but I'll figure something out and take care of it soon.

**Comment by jdesrosiers** [comment]
I added the custom Error class. I'm still not super happy with it. The part I don't like is that you have to know to look for the validation results in custom property `output`. I'm concerned that people won't know to look for this field. But, it's not good enough the way it is and I didn't come up with a better option, so this will have to do.
